### ISSUE TITLE
Mouse scroll wheel settings ignored on Windows 10

### ISSUE THREAD

**Issue by kuro68k** [Yubico/yubioath-flutter#1000]
Version: 6.0.0.0

When scrolling through the list with the mouse wheel, scrolling is very slow. One small step at a time. In Windows my scroll wheel is set to scroll 6 lines at a time. Apparently Authenticator ignores that setting, making the scroll wheel very awkward to use.

I have a basic mouse, no fancy mouse software, just Windows USB HID drivers.

**Comment by fdennis** [comment]
Hi,
This seems to be an issue with Flutter. They are aware of it and have a fix in place (https://github.com/flutter/engine/commit/17725f1711d2c3ca60471ea2f05d1792f8776234). We will update the version of Flutter for the next release and that should solve it. We can keep this issue open until then.

**Comment by dainnilsson** [comment]
This should now work as expected in Yubico Authenticator 6.2.
