### ISSUE TITLE
[Android] nfc ndef does not work

### ISSUE THREAD

**Issue by Sorunome** [Yubico/yubioath-flutter#1021]
The only way soru found to enable nfc ndef was by changing the setting for what to do on tapping the yubikey, and the copy to clipboard ones don't seem to do anything at all

**Comment by AdamVe** [comment]
Hi, thank you for reporting as the app should be copying NDEF information to clipboard. Could you please try following and report back the result:
- set the option "On YubiKey NFC tap" to "Copy OTP to clipboard"
- go to home-screen (leave Yubico Authenticator app)
- tap the YubiKey

Expected: a notification toast appears with information that OTP was copied to clipboard, the OTP value is present in the system clipboard and can be pasted into other applications.

The app currently does not copy the OTP to clipboard when it is running in foreground.

**Comment by AdamVe** [comment]
Could you let us know versions of Yubico Authenticator and Android/device you are using.

Yubico Authenticator only intercepts NDEF tags in the format of `https://my.yubico.com/...`

**Comment by Sorunome** [comment]
ah, soru just has a plain text one, without any url prefix. That would explain that part. In the past it was possible to have the OTP/static password entry next to the TOTP ones, is that not possible anymore?

**Comment by AdamVe** [comment]
The app itself only shows TOTP codes from the oath applet, but should copy the OTP/static password from NDEF to clipboard.

> ah, soru just has a plain text one, without any url prefix.

The _plain text password_ you mention, how was it added to the key?

**Comment by Sorunome** [comment]
static password for MOD keyboard layout generated on the key itself, via ykman. And then configured ykman to put that slot into ndef in text mode w/o a prefix

**Comment by AdamVe** [comment]
In that case, Yubico Authenticator should work if you setup your ndef type as URI:
`ykman otp ndef --ndef-type URI 1`

It will add the needed prefix automatically and will serve the password you already have in the slot.

**Comment by Sorunome** [comment]
yeah, soru wanted to avoid the uri stuff as she didn't have the spoons to set up her own service for copying to clipboard ^^ as, in theory, if e.g. yubico was taken over, the sites javascript could be replaced to read out the ancor.

That being said, is the old functionality for just text planned to be added again?

**Comment by AdamVe** [comment]
I will discuss this with the team and update this thread with answer. 

Please also see the `ykman otp ndef -h` documentation. With the URI ndef type it is possible to exchange the prefix independently on the static password.

**Comment by Sorunome** [comment]
That's sad to hear, especially since the non-flutter one had this :/ thank you for the information, though! And a separate scheme should help a bit with this 👍

3. 4. 2023 15:01:53 Adam Velebil ***@***.***>:
