### ISSUE TITLE
[Linux][UX] More options for exiting the application

### ISSUE THREAD

**Issue by t3hmrman** [Yubico/yubioath-flutter#1029]
For some of us running a minimal window manager like `bspwm`, there is no option to exit after starting the app -- I'd love to have one of the following:

- "Exit"/"Close"/"Quit" in the LHS hamburger menu
- Response to Ctrl+Q/Mac+Q from the keyboard

Apologies if I've somehow missed how to exit the application, or if this is really not a usual case.

**Comment by dainnilsson** [comment]
Ctrl+Q should work in the latest version.

**Comment by t3hmrman** [comment]
Thanks @dainnilsson!
