### ISSUE TITLE
[Android] ‘On YubiKey NFC tap’ setting is missing a ‘Do nothing’ option

### ISSUE THREAD

**Issue by kaoneko** [Yubico/yubioath-flutter#1110]
In the settings of the Android app we have the setting _On YubiKey NFC tap_ which can be set to one of the following:

- Launch Yubico Authenticator
- Copy OTP to clipboard
- Launch app and copy OTP

What I'm missing here is an option to do absolutely nothing. Use case: I use another app that uses challenge-response over NFC to unlock a password database, and when it interfaces with the YubiKey I don't want to launch the Yubico app nor copy the OTP. I just want to stay in the app I'm using at that moment while also not putting sensitive data into the clipboard.

The launching of the Yubico app or copying the OTP doesn't prevent me from succesfully authenticating with that other app, but it's annoying nevertheless. My workaround has been to set Tasker to handle NFC scans and have it do absolutely nothing.

**Comment by kaoneko** [comment]
P.S. It confuses me that the app uses _OTP_ here while what the _Copy OTP to clipboard_ option actually does is copy the static password. Am I misunderstanding something here or is this mislabelled?

**Comment by kaoneko** [comment]
Great!

Aha, I get it. The most confusing thing about the _Copy OTP to clipboard_ option is that the app's main use is accessing TOTP codes stored on the key, colloquially known as _OTP_ codes right. So I expected the app to somehow be context aware when activating this option and copying the (T)OTP code of the service I'm logging into to the clipboard (which would be quite handy).

I have no experience whatsoever with Yubico OTP and know nothing about it, so I have no idea what the result of this option is when using Yubico OTP.

**Comment by AdamVe** [comment]
Hi @kaoneko, we have just released [Yubico Authenticator 6.3.1](https://github.com/Yubico/yubioath-flutter/releases/tag/6.3.1) which adds a new option for the "On YubiKey NFC tap" preference: _Do Nothing_. Thanks for taking the time reporting the issue!
