### ISSUE TITLE
App crashes on macOS 14 Developer Beta

### ISSUE THREAD

**Issue by vasimi** [Yubico/yubioath-flutter#1113]
Hi,
I tried out Yubico Authenticator installed from Mac App Store (version 6.2.01) on macOS 14 Developer Beta and unfortunately, it crashes immediately after start.

```
> /Applications/Yubico\ Authenticator.app/Contents/MacOS/Yubico\ Authenticator
06:40:21.694 [desktop.init] INFO: Logging initialized, outputting to stderr
06:40:21.702 [desktop.init] INFO: Starting Helper subprocess: /Applications/Yubico Authenticator.app/Contents/Resources/helper-arm64/authenticator-helper
06:40:21.708 [desktop.init] INFO: Helper process started
[1]    15610 trace trap  /Applications/Yubico\ Authenticator.app/Contents/MacOS/Yubico\ Authenticator
```

I understand you may not have the capacity to support new versions of OSes before their release to the end-users, but I guess you'll want to fix this before macOS 14 gets released.

**Comment by fdennis** [comment]
Thank you for the report.
We will try to verify this when the official version of macOS 14 is released. The issue you are seeing might be solved in a later beta, since they are frequently releasing new ones.

**Comment by ojsef39** [comment]
@vasimi try the version from their website instead of the app store, im also on macOS 14DB and had not even once a crash :)

**Comment by danieldymondnz** [comment]
> @vasimi try the version from their website instead of the app store, im also on macOS 14DB and had not even once a crash :)

Can confirm the app launches on Beta 6 (23a5328b)!
