### ISSUE TITLE
[Linux] Installing an icon pack fails

### ISSUE THREAD

**Issue by christian-scheible** [Yubico/yubioath-flutter#1122]
I'm attempting to install an icon pack on Manjaro Linux.

However, I'm encountering the following exception:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FileSystemException: Rename failed, path = '/tmp/yubioathZOVQAJ/unpack' (OS Error: Ungültiger Link über Gerätegrenzen hinweg, errno = 18)
#0      _checkForErrorResponse (dart:io/common.dart:42)
#1      _Directory.rename.<anonymous closure> (dart:io/directory_impl.dart:200)
<asynchronous suspension>
#2      IconPackManager.importPack (package:yubico_authenticator/oath/icon_provider/icon_pack_manager.dart:169)
<asynchronous suspension>
#3      _ImportActionChip._importAction (package:yubico_authenticator/oath/icon_provider/icon_pack_dialog.dart:183)
<asynchronous suspension>
```

Moreover, there is no error message displayed in the user interface when this occurs. Instead, there is a continuous spinning wheel without any resolution.

**Comment by j-lakeman** [comment]
Confirmed for Debian GNU/Linux 12 (bookworm) x86_64

**Comment by AdamVe** [comment]
Thank you for reporting. The stack trace is identical to #1051, which has been already fixed. The fix will be released with next version of Yubico Authenticator.
