### ISSUE TITLE
No custom icons for iOS and MacOS?

### ISSUE THREAD

**Issue by ojsef39** [Yubico/yubioath-flutter#1175]
In [this release notes](https://github.com/Yubico/yubioath-flutter/releases/tag/6.2.0), it is stated that icon support was added.

It works for me on my work android, but on my Mac and iOS device I don't see that option.

It would be nice to have it on those devices too, thanks in advance :)

**Comment by AdamVe** [comment]
Hi, Yubico Authenticator 6.2.0 on Mac OS supports custom icons the same way as on Android, let us know if you have any issues with it. For iOS, please refer to the following project https://github.com/Yubico/yubioath-ios :)

**Comment by ojsef39** [comment]
Sorry, feeling so stupid right now. i was on the wrong version on mac…

On iOS im on the right version though, thanks for the link i will create an issue there instead :) @AdamVe
