### ISSUE TITLE
Calculate with ⌘+R

### ISSUE THREAD

**Issue by ojsef39** [Yubico/yubioath-flutter#1176]
I often have the same OTP open and when it expires i just instinctively want to press ⌘+R and then ⌘+C and then tab back into the last application.

I would really love to see this as an option in the future :) 

im no ux designer (just made this with my screenshotting tool) but this is approx what mean
![image](https://github.com/Yubico/yubioath-flutter/assets/43563019/4bf51221-4b35-4446-9961-576a1a0f3e4d)

**Comment by elibon99** [comment]
You can actually achieve a similar result using ⌘+C. This will calculate a new OTP (if expired) and copy it to the clipboard. However, we recognize the value of having a dedicated ⌘+R shortcut for explicit refresh, and we are planning on implementing support for that.

**Comment by ojsef39** [comment]
> You can actually achieve a similar result using ⌘+C. 
Ohh, thanks, I didn't notice that that's also possible 

> However, we recognize the value of having a dedicated ⌘+R shortcut for explicit refresh, and we are planning on implementing support for that.
Thank you very much! Appreciate it ;)

**Comment by elibon99** [comment]
This has now been implemented in #1212 and merged. We hope to include this feature in the next release.
