### ISSUE TITLE
CWE-212: Improper Removal of Sensitive Information

### ISSUE THREAD

**Issue by sylvainpelissier** [Yubico/yubioath-flutter#1229]
I have tested the Yubico authenticator version [6.3.0](https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-latest-linux.tar.gz), the latest available version to the time of writing. My tests have been made on the Linux version but I'm confident that the same problems are on other operating system versions. 

I noticed that two process are ran, `authenticator` and `authenticator-helper`, while the application is running. If a user have entered their PIN or passwords in the application, I have noticed that those credentials stay in memory of those process even after the removal of the key.

After the credentials have been entered, once the Yubikey is removed, the  `authenticator-helper` process can be dumped with:
```bash
$ sudo gcore $(pidof authenticator-helper)
```

The WebAuthn PIN can be recovered with:
```bash
$ strings core.5080| grep \"pin\"
{"kind":"command","action":"unlock","target":["usb","23866552","fido","ctap2"],"body":{"pin":"12345678"}}
```

The oath password can be recovered with:
```bash
$ strings core.5080| grep \"password\"
{"kind":"command","action":"derive","target":["usb","23866552","ccid","oath"],"body":{"password":"12345678"}}
```

The oath password is also present in a dump of the  `authenticator` process but less easily recoverable with the tool `strings`.

To our knowledge it seems not to be critical problems since the attacker needs to have access to the machine an run `gcore` command with root permission. However, this contradicts your statement that ["*Your credential stays safe in the secure element of the YubiKey*"](https://www.yubico.com/products/yubico-authenticator/).

**Comment by dainnilsson** [comment]
Thank you. We consider this to be out of scope of the threat model of this application. A user with administrator/root access to the system will be able to capture user-provided credentials in a number of different ways, such as by keylogger or screen capture.

Our website's claim which you mention is using the word "credential" to refer to the cryptographic keys used to generate the OTPs for logging into accounts, not the user-provided "credentials" that are the subject of this issue. The "cannot be extracted" part is in reference to the YubiKey's secure element. During provisioning of credentials for the YubiKey these values may exist outside of the secure element in application memory.
