### ISSUE TITLE
Move strings from logging.dart to arb files

### ISSUE THREAD

**Issue by Daviteusz** [Yubico/yubioath-flutter#1237]
Strings found in logging.dart are not translatable. Please move them to arb files.
https://github.com/Yubico/yubioath-flutter/blob/8a2ab476b98530f4369a18fdf67cf0fbf433d7d8/lib/app/logging.dart#L116-L126

**Comment by dainnilsson** [comment]
These are intentionally left out. The reasoning here is that these warning need to be clearly visible, and do not show up under "normal" use. A translation should not be able to change their meaning or hide them. Granted, this does of course rely on the user understanding the strings, so it's not ideal. But we will have no way of ensuring that they are correct for all submitted translations, so this was deemed the "less bad" solution.
