### ISSUE TITLE
[Android] Manual add: account name field as email address

### ISSUE THREAD

**Issue by pcrock-thmdo** [Yubico/yubioath-flutter#1255]
I migrated a lot of MFA accounts to my Yubikey today. For many of my accounts, instead of reconfiguring TOTP for each account, I just copy / pasted the TOTP secrets from my old authenticator app to the Yubikey app. So I chose the "manual" method rather than the QR code method when adding new accounts to my key.

However the "Account name" field is pretty annoying. 90% of my accounts use my email address as the account name, and autocorrect kept trying to mess with the text I was entering.

Suggestion: Mark the account name field as an email field. I'm no Android / flutter developer, but I assume this is a minor tweak that would be more ideal, even if the user was inputting a non-email username.

**Comment by AdamVe** [comment]
Hi, do you have any examples of the issue? I cannot reproduce this when pasting invalid/incorrect strings into the Account name field in version 6.3.0 when using Gboard in English. I tried pasting into the field followed by writing or switching focus to different field, but the autocorrect never executes for me.

**Comment by pcrock-thmdo** [comment]
Minor clarification: I only pasted the secret from another app, and manually typed the account name.

Autocorrect's behavior for me (on Graphene OS) worked like this for an email address like `first.last@example.com`:

1. type `first` then `.`: autocorrect capitalizes `first.` -> `First.`
2. type `last@example` then `.`: autocorrect changes it to ` Last @example.`

**Comment by AdamVe** [comment]
Thanks for the clarification!

**Comment by pcrock-thmdo** [comment]
sorry i've been editing my last answer for the past 5 minutes :smile:

i'm done editing it now

**Comment by AdamVe** [comment]
Hi @pcrock-thmdo, we have just released [Yubico Authenticator 6.3.1](https://github.com/Yubico/yubioath-flutter/releases/tag/6.3.1) which removes autocorrect from text fields through out the app. Thanks for taking the time reporting the issue!
