### ISSUE TITLE
macOS App Store builds have quarantine bit set?

### ISSUE THREAD

**Issue by winterqt** [Yubico/yubioath-flutter#1340]
For at least the last two Mac App Store releases (6.3.0 and 6.3.1), the binaries have the `com.apple.quarantine` bit value set to `0181;65707e75;Chrome;`, which causes the following dialog upon every update:

<img width="258" alt="image" src="https://github.com/Yubico/yubioath-flutter/assets/78392041/e49e2e1a-f80a-4ced-96dc-9873c4839d0b">

**Comment by fdennis** [comment]
This should now be fixed in the latest version, 6.4.0. Could you check if that is the case?
