### ISSUE TITLE
Feature request for Kotlin/Multiplatform

### ISSUE THREAD

**Issue by kristoffer-paulsson** [Yubico/yubioath-flutter#1419]
Sorry for not using another thread, but the helpdesk directed me here.

Hi Yubico Developer Program, here is my suggestion for a simple development solution of mobile apps utilizing Yubico features.
Have you realized that JetBrains have release a new Kotlin/Multiplatform standard in version 1.9.22.
I suggest that you merge your iOS and Android kits into a common codebase, it will be so easier if you do
and save time for app developers alike.

Best regards
Kristoffer
An App maker.

P.S.

Look at https://kmp.jetbrains.com/

D.S.

**Comment by dainnilsson** [comment]
Thanks for the suggestion. We are aware of Kotlin/Multiplatform. We have no plans on rewriting the app as of now.
