### ISSUE TITLE
"Load Icon Pack" not working

### ISSUE THREAD

**Issue by jh-devv** [Yubico/yubioath-flutter#1421]
The opening file browser is not opening?

This is on NixOS and Hyprland with the `xdg-desktop-portal-gtk`?

It should work if Flutter uses `xdg-open` like api's?

**Comment by AdamVe** [comment]
Hi, thanks for reporting. This issue maybe the same as #1399. We currently use a plugin for showing system dialogs and it has problems on Linux. We are investigating how to fix this.

Do any of the workarounds in #1399 work for you?

**Comment by jh-devv** [comment]
> Hi, thanks for reporting. This issue maybe the same as #1399. We currently use a plugin for showing system dialogs and it has problems on Linux. We are investigating how to fix this.
> 
> Do any of the workarounds in #1399 work for you?

Thanks!

**Comment by AdamVe** [comment]
I am closing this issue, the conversation will continue in the linked ticket.
