### ISSUE TITLE
Touch required does not work with NFC

### ISSUE THREAD

**Issue by hmhmoups** [Yubico/yubioath-flutter#1544]
Hello,

I noticed that touch required does not work with NFC on android (I tried with two different yubikey 5NFC.). The app asks to tap the key to reveal the code despite having selected touch required. 
It works as expected via usb.

Is it the default behavior or a bug?

I am on android 14 and I use v6.4.0. 

Thanks in advance for the help.

**Comment by dainnilsson** [comment]
Are you referring to the physical action of pressing the gold sensor which is required over USB? If so, that sensor is not powered over NFC, and the act of tapping the YubiKey itself against the NFC reader replaces the sensor tap.

**Comment by hmhmoups** [comment]
Yes indeed I was referring to the gold sensor.
So can be closed.
Thanks
