### ISSUE TITLE
Improve usability of OATH

### ISSUE THREAD

**Issue by upsuper** [Yubico/yubioath-flutter#1576]
I recently switched from the old yubioath-desktop 5.1.0 shipped with Ubuntu to this app because the previous version becomes [broken](https://bugs.launchpad.net/ubuntu/+source/yubioath-desktop/+bug/2067197) with Ubuntu 24.04.

However, despite that yubioath-flutter has a higher version and gets updated frequently, I find it quite frustrating to use.

In the old app,
* all my 20+ accounts are laid on the window, and I can scan it quickly to find the account I need, then
* click the account, and
* tap the button on the key

now I can switch to the target window and paste the code in.

However, with the new app,
* the list is very bloated and it's impossible to show all my accounts in one view, so I have to type to search, then
* click the account, then
* click "Calculate", and
* tap the button on the key, then
* click "Copy to clipboard"

only now I can switch to the target window and paste the code in.

This takes twice as many steps to complete the same task of generating the TOTP code and having it available in the clipboard.

Is this something that can be improved? The old flow is much nicer, and I don't see why it shouldn't work like that.

**Comment by upsuper** [comment]
Thanks for the tips, they are very useful! It would be great if they are easily discoverable, especially the long press / double click one.

**Comment by del-leehopper** [comment]
I agree, I requested this back in November 2023. Feel free to add a thumbs up there:

https://github.com/Yubico/yubioath-flutter/issues/1257

**Comment by braathen** [comment]
@upsuper 

Gridview of OATH credentials and passkeys is now available in the new 7.1 version, hopefully it will allow you to get a better overview of your credentials. Also note that it's possible to collapse and hide the left and right side menus for even more space.

**Comment by upsuper** [comment]
@braathen Glad to see the grid view is back now! Thanks for working on this and letting me know.
