### ISSUE TITLE
Official Flatpack and Snapsupport

### ISSUE THREAD

**Issue by ripper81** [Yubico/yubioath-flutter#1603]
Hi, it would be great to have yubico authenticator available as an official Flatpak and Snap package. The way the app is provided right now on desktop linux is not convienient in my opinion.

This is an enduser tool needed to use an important feature. It should be easy to install and to update. Using modern package formats might also help whith distribution compatibility.

**Comment by AdamVe** [comment]
Hi, thank you for using YubiKeys and Yubico Authenticator.

We currently do not have plans to maintain any Linux packaging systems, including Flatpak, Snap, or AppImage. Instead, we encourage the open-source community to utilize our source code and binary distribution to create the packages that are needed, and we fully support these initiatives.

**Comment by schlagi123** [comment]
Hi, if you full supporty the community, it would greate, if the flatpack could be verified. Some distributions do not show this app by default because of this missing verification because this could be a security risk. 

https://flathub.org/apps/com.yubico.yubioath
https://github.com/flathub/com.yubico.yubioath/issues/83

**Comment by RoyalOughtness** [comment]
@AdamVe FYI, verification on flathub does *not* require Yubico to maintain the package. It can also be a stamp of approval from the developers indicating their authorization of a third-party packager:

 https://docs.flathub.org/docs/for-app-authors/verification

> Verification is the process by which Flathub and developers confirm that an app is published by the original developer **or an authorized party**.

Given your intent to fully support these initiatives, it would be a big win if you went through these steps especially for such a security-critical app. It is [relatively straightforward](https://docs.flathub.org/docs/for-app-authors/verification/#website) and a one-time process.
