### ISSUE TITLE
[android] Moto G Pure: Connecting too briefly?

### ISSUE THREAD

**Issue by Andersama** [Yubico/yubioath-flutter#1731]
I've now tried a Yubikey 5 NFC and Yubikey 5C with the same results, I have a suspicion I'd be dealing with the same problem with any model. In the app there's no recognition that a device has been connected. I don't get a prompt that a usb device has been connected like I would for file transfers etc. However if I'm in the USB Preferences menu both devices appear to be doing something for a brief moment as the menu is flashing between a disabled and enabled state very rapidly. 

I've found seemingly unrelated articles about usb devices having problems that sounds vaguely similar. I can only assume there's some android setting which is not set properly. I'd be happy to log any debug info if anyone can walk me through how to do that. I found documentation saying to report issues about android here, which seems a bit strange because I think this is more to do with android than this app.

I can now confirm a similar model phone works, so I suspect its an android setting causing problems.

**Comment by AdamVe** [comment]
Hi! Sorry to hear that - could you let us know what Android version is your device running? Some phones have a feature called USB OTG which needs to be enabled otherwise the OS will ignore a connected device. 

To help to understand what is broken, could you create a TRAFFIC log in the app and share it with me? The log might expose user data, so please hide all the received bytes.

**Comment by Andersama** [comment]
Sorry, been distracted with holidays, sure I'll try to create a traffic log. How do I go about doing that?

**Comment by AdamVe** [comment]
Thank you for the update. I’m afraid the USB adapter could be causing the connection issues, as I’ve had a similar experience. What type or brand of adapter are you using? Could the blinking be an indication that it’s continuously reconnecting?

**Comment by Andersama** [comment]
Well, I'd have agreed with you that it was the adapter if only one version of the key was a problem. I can only guess that USB OTG setting was in the wrong state and it took a soft reset for it to "fix itself". Although it wasn't immediate which is especially confusing.

**Comment by AdamVe** [comment]
Glad it got sorted out. Dealing with this kind of connectivity issues can be tough to troubleshoot, thanks for keeping us in the loop.
