### ISSUE TITLE
[feature request] Provide Android releases somewhere else in addition to GooglePlay 

### ISSUE THREAD

**Issue by ngrigoriev** [Yubico/yubioath-flutter#1736]
It would be really great if Android app releases were available somewhere else in addition to Google Play. Not everyone using Android agrees to use Google Play and, thankfully, there are many alternatives: GitHub itself, F-Droid, Accrescent...

**Comment by ngrigoriev** [comment]
@dainnilsson Sorry, my bad, I was looking at the last release and just realized that it is marked as "desktop-only"! :(

**Comment by dainnilsson** [comment]
No worries!
