### ISSUE TITLE
Enhancement: Add keyring support for storing device password

### ISSUE THREAD

**Issue by JGoutin** [Yubico/yubioath-flutter#390]
Currently, when checking "remember" when entering the device password, the utility store the (derived) device password in the configuration file `~/.ykman/oath.json` (ref: https://github.com/Yubico/yubioath-desktop/blob/master/py/yubikey.py#L263).

The idea is to store it in the OS keyring (like Gnome keyring, Kwallet, ...) instead if available. This may add an extra level of security.

This can be done easily with the following package: https://github.com/jaraco/keyring

**Comment by dagheyman** [comment]
Thanks! It's a good suggestion and we'll try to investigate what effort it would take to add this.

**Comment by asvc** [comment]
...can this be also considered for a Windows platform? Perhaps interface with the "Vault" via Powershell: https://gallery.technet.microsoft.com/scriptcenter/PowerShell-Credentials-d44c3cde

**Comment by JGoutin** [comment]
For information, the [keyring library](https://github.com/jaraco/keyring) also support windows using [Windows Credential Locker](https://docs.microsoft.com/en-us/windows/uwp/security/credential-locker)

**Comment by dainnilsson** [comment]
It is actually! It was added to `ykman` 5.0.0 and included in Yubico Authenticator 6.0. Please do try it out and let us know if you have problems with it!

**Comment by JGoutin** [comment]
Awesome, thanks !
