### ISSUE TITLE
Yubikey authenticator no longer shows secret field during QR code import

### ISSUE THREAD

**Issue by JohnVillalovos** [Yubico/yubioath-flutter#649]
- Yubico Authenticator version:  5.0.4
- Operating system and version: Windows 10
- YubiKey model and version: All
- Bug description summary: 

Previous versions of Yubico Authenticator (4.x) when doing a QR code import would show the three fields (Provider name, account name, and the secret). Now it no longer shows the secret :(

I found the feature of showing the secret useful as I take the information and save the data and then use GPG to encrypt it and store a backup.

I could not find a setting to enable showing the secret, but maybe I just missed it.

**Comment by braathen** [comment]
Thanks for the feedback, I agree that we probably need to find a way to bring this possibility back.
