### ISSUE TITLE
White screen when using 3 screens and secondary is main display

### ISSUE THREAD

**Issue by timovd** [Yubico/yubioath-flutter#658]
- Yubico Authenticator version: 5.0.4 (x64)
- Operating system and version: Win10 1909
- YubiKey model and version: 5 NFC
- Bug description summary: White screen when using 3 screens and secondary is main display

**Steps to reproduce**
I have a 15,4" laptop with 1920 * 1080 resolution (150% scaling)
Two external screens 1920 * 1200 (100%/no scaling)
The second sceen is my main display
Start Yubico Authenticator on your 2nd screen (main screen)

I also tried with no scaling on my laptop screen and this is still reproducable

**Expected result**
Yubico Authenticator should show "Insert your Yubikey"

**Actual results**
Empty window in Yubico Authenticator

**Other info**
Workaround: Move the application to the 1st screen, close the application and open the application again (on the 1st screen).

Not reproducable with 2 screens and 2nd screen is main display.

**Comment by AUThomasCH** [comment]
I can confirm and reproduce this issue. Thanks for the workaround.
Tested on Windows 10 20H2

**Comment by jeppz** [comment]
I can also confirm and reproduce this issue. Sometimes it freezes and only workaround I've found for that is
registry  HKEY_CURRENT_USER\Software\Yubico\Yubico Authenticator\x c8 (200) to force it to display 1 again.

Getting same problem when app is closed on 3rd screen as well, only starts when closed on 1st display. 
Display layout 2, 1 Primary, 3 
Yubico Authenticator version: 5.0.4 (x64)
OS: Win10 1909
YubiKey modeln: 5 NFC

**Comment by fdennis** [comment]
Hi,
Do I understand correctly that the app opens but it's just white? It does not even say "Insert your YubiKey"?

**Comment by timovd** [comment]
@fdennis Correct!

**Comment by jeppz** [comment]
@fdennis  thats correct

**Comment by fdennis** [comment]
And this happens with three monitors, but not with two?

**Comment by timovd** [comment]
@fdennis exactly, but only when the second monitor is the main display.

**Comment by fdennis** [comment]
@timovd Does it make any difference if you set the environment variable `QT_OPENGL` to `angle `or `software `before launching the app?

**Comment by jeppz** [comment]
@fdennis Setting the QT_OPENGL env variable to either angle or software fixed the issue for me.

**Comment by TheNoobWar** [comment]
This issue is still reproducible when using a program such as [PowerToys' Fancy Zone feature: "Move newly created windows to their last known zone."](https://learn.microsoft.com/en-us/windows/powertoys/fancyzones#settings)
