### ISSUE TITLE
Bug: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 1: invalid start byte

### ISSUE THREAD

**Issue by Lunarequest** [Yubico/yubioath-flutter#755]
- Yubico Authenticator version: Yubico Authenticator 5.1.0
- Operating system and version: Linux fedora 35 flatpak
- YubiKey model and version: 5nfc
- Bug description summary: 
Currently in fedora 35 the flatpak does not work, this is a reproducible issue. currently an error throws out an error stating `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 1: invalid start byte` when the log level is set to DEBUG 

Steps to reproduce
---
1. Plug in the yubikey
2. attempt to do anything with the yubikey

Expected result
---

setting pin succeeds

Actual results
---

A generic error message is shown 

Other info
---

I have used the udev rule as per support articles https://raw.githubusercontent.com/Yubico/libu2f-host/master/70-u2f.rules. I am the comaintainer of the flatpak.

**Comment by fdennis** [comment]
Have you tried the AppImage (and, if at all possible, the Snap) and do they have the same issue? If not, then this only applies to the Flatpak. In either case, it is difficult for me to say anything about this issue, since I cannot reproduce it and have never seen it before. If you have more information, please let us know.

**Comment by Lunarequest** [comment]
I have tried the appimage and it works there, I would like to resolve the issue in the flatpak since it doesn't effect archlinux but fedora 35.

**Comment by fdennis** [comment]
@Lunarequest Unfortunately I cannot say anything new. This seems to be an issue with scard. I have never seen this issue with our AppImages or Snaps. I have only heard it from Flatpak users on Fedora 35. Perhaps this is an issue with Fedora 35? Or with scard on Fedora? What do you think?

**Comment by Lunarequest** [comment]
I believe its an issue with fedora in some form, not sure what about fedora 35 causes the issue

**Comment by nevun** [comment]
Here is a mininal reproducer at least:

```
$ flatpak run --command=sh --devel com.yubico.yubioath
[📦 com.yubico.yubioath ~]$ cat > /tmp/list.py
from smartcard import System
System.readers()
[📦 com.yubico.yubioath ~]$ python3 /tmp/list.py
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf5 in position 0: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/list.py", line 2, in <module>
    System.readers()
  File "/app/lib/python3.9/site-packages/smartcard/System.py", line 41, in readers
    return smartcard.reader.ReaderFactory.ReaderFactory.readers(groups)
  File "/app/lib/python3.9/site-packages/smartcard/reader/ReaderFactory.py", line 58, in readers
    zreaders += fm(groups)
  File "/app/lib/python3.9/site-packages/smartcard/pcsc/PCSCReader.py", line 112, in readers
    pcsc_readers = __PCSCreaders__(hcontext, groups)
  File "/app/lib/python3.9/site-packages/smartcard/pcsc/PCSCReader.py", line 43, in __PCSCreaders__
    hresult, readers = SCardListReaders(hcontext, groups)
  File "/app/lib/python3.9/site-packages/smartcard/scard/scard.py", line 640, in SCardListReaders
    return _scard.SCardListReaders(hcontext, readergroups)
SystemError: <built-in function SCardListReaders> returned a result with an error set
[📦 com.yubico.yubioath ~]$
```

**Comment by Lunarequest** [comment]
I tried reproducing this on nixos, it looks like its a fedora specific issue
