### ISSUE TITLE
Upgrade to Qt 6

### ISSUE THREAD

**Issue by winterqt** [Yubico/yubioath-flutter#760]
(Specifically Qt 6.2+, but Qt 6 was a snappier title.)

This would make Yubico Authenticator, among other enhancements and fixes, native to Apple silicon.

See the [Qt 6 porting guide](https://doc.qt.io/qt-6/portingguide.html) for information on upgrading (which should be fairly simple, as there are a minimal amount of breaking changes between Qt 5.15 and Qt 6).

**Comment by ridicolos** [comment]
Would love to see the native support of m1 - because it would reduce the loading times and the app could be a little snappier. (if you want your keys, you often want to get them fast)

**Comment by fdennis** [comment]
We are currently working on version 6 of the app, and will have more to share on this shortly. Native M1 support for MacOS will be coming in this release.

**Comment by thierrygoldwaser** [comment]
> We are currently working on version 6 of the app, and will have more to share on this shortly. Native M1 support for MacOS will be coming in this release.

Great to hear, it is almost the last app I have which is not M1-native.
