### ISSUE TITLE
Better support for multiple keys

### ISSUE THREAD

**Issue by acdha** [Yubico/yubioath-flutter#765]
- Yubico Authenticator version: 5.1.0
- Operating system and version: macOS 12.0.1
- YubiKey model and version: n/a
- Bug description summary: 

If you have multiple Yubikeys present, the USB enumeration order controls which set of TOTP codes will be visible when the app starts. Selecting a different key is non-obvious, requiring use of the hamburger menu and the disclosure diamond next to the active key (a UI widget which would generally display additional details for the current key rather than other keys).

This could be improved in several ways:

* Automatically select the key with secrets if only one is present — I keep mine on my NFC key so I can share with my phone, so this would address my needs completely.
* Display a merged view showing _all_ of the codes from every key, relying on the user tapping the one which is blinking when needed.
* Better UI cues for multiple keys — for example, using a standard selection dropdown list would make it immediately obvious that this can be changed and either not collapsing the hamburger menu on non-tiny displays or moving the selection widget out of it since that needs to be used more frequently than the settings. On my 14" MacBook Pro display, I can display as many TOTP secrets as fit on a single key using roughly half the screen so we have plenty of room for a selection widget.

**Comment by Chantology** [comment]
Nothing to add here, only want to agree that improving UI for multiple keys is very useful!
