### ISSUE TITLE
TOTP when pcscd is not running

### ISSUE THREAD

**Issue by smvoss** [Yubico/yubioath-flutter#768]
- Yubico Authenticator version: v5.1.0
- Operating system and version: Arch linux
- YubiKey model and version: 5 NFC
- Bug description summary: TOTP do not show when password protected, if `pcscd` is not running (expected), although no information is given to the user that is the root of the issue.

Steps to reproduce
---

Do not have `pcscd.service` running, and do not have the socket available. This is the standard situation after a fresh install.

Expected result
---

TOTP codes available OR a message / action button available to enable required service.

Actual results
---

Application reports that there are no keys available, with no debug information available. Looks like a fresh key.

Other info
---

I stumbled upon this thread due to my TOTP not working on Arch Linux, however the answer was available in here:

> Do you have the `pcscd` daemon running?

Is it possible to have a popup warning the user that it's not running / have the installer activate the service? Seems silly that I had to google to figure this out (note: it does spit out a warning if it's not running, so the application seems to do this error detection but unfortunately not prompt the user in a meaningful way). An interesting thing I noticed is that the `pcscd` service will leave a socket around which the desktop app does seem to poke and wake up if it's available - so it only needs to be started once (per boot?).

I'm not entirely sure what the correct solution is for something like this, although I don't think the user should be manually enabling the service. Maybe a button in the app to allow you to enable / start the service if not running?

Thanks!

**Comment by leftbit** [comment]
Still an issues with Yubico Authenticator 6.0. Just installed on a fresh linux mint - have to start pcscd via terminal.

**Comment by dainnilsson** [comment]
@leftbit you should be seeing something like this, is that not the case for you?

![image](https://user-images.githubusercontent.com/140781/202687516-9504f00a-d02a-46db-b760-c7712daa6add.png)

**Comment by leftbit** [comment]
Yes. pcscd is installed. But by default it is configured to start on demand:

```
sudo systemctl status pcscd.service
● pcscd.service - PC/SC Smart Card Daemon
     Loaded: loaded (/lib/systemd/system/pcscd.service; indirect; vendor preset: enabled)
     Active: active (running) since Fri 2022-11-18 11:50:40 CET; 6min ago
TriggeredBy: ● pcscd.socket
       Docs: man:pcscd(8)
   Main PID: 6829 (pcscd)
      Tasks: 6 (limit: 18965)
     Memory: 1.2M
        CPU: 51ms
     CGroup: /system.slice/pcscd.service
             └─6829 /usr/sbin/pcscd --foreground --auto-exit
```

Looks like the `pcscd.socket' should be accessed by the Authenticator to trigger the pcscd service.

```
sudo systemctl status pcscd.socket
● pcscd.socket - PC/SC Smart Card Daemon Activation Socket
     Loaded: loaded (/lib/systemd/system/pcscd.socket; disabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-11-18 10:45:15 CET; 1h 17min ago
   Triggers: ● pcscd.service
     Listen: /run/pcscd/pcscd.comm (Stream)
     CGroup: /system.slice/pcscd.socket
```

**Comment by dainnilsson** [comment]
Hmm. That's something I would expect https://pyscard.sourceforge.io/ would do. I can take a look and see if I can figure anything out.

**Comment by leftbit** [comment]
Just rebooted my machine to get the initial states:

```
sudo systemctl status pcscd.socket
[sudo] Passwort für thomas:         
○ pcscd.socket - PC/SC Smart Card Daemon Activation Socket
     Loaded: loaded (/lib/systemd/system/pcscd.socket; disabled; vendor preset:>
     Active: inactive (dead)
   Triggers: ● pcscd.service
     Listen: /run/pcscd/pcscd.comm (Stream)
```

Looks like the trigger is dead... weird.

**Comment by dainnilsson** [comment]
Looks like it might be this: https://ludovicrousseau.blogspot.com/2022/10/ubuntu-2204-and-pcscd-auto-start-failure.html

**Comment by leftbit** [comment]
Can confirm too - enabling the socket makes Authenticator start pcscd. :) 

One for the FAQ, I guess.

**Comment by smvoss** [comment]
I think that's fine, although I think it's something the application should be able to detect and report. This takes some if the onus off the end user and we don't have to dig into faq to find this info out

**Comment by AdamVe** [comment]
Hi @smvoss. We detect if pcscd is not running and the app shows that information. We can't really do much more in the app. This needs to be fixed in ubuntu (see https://bugs.launchpad.net/ubuntu/+source/pcsc-lite/+bug/1971984)
