### ISSUE TITLE
Cannot cancel touch action in case of missclick

### ISSUE THREAD

**Issue by elboletaire** [Yubico/yubioath-flutter#813]
- Yubico Authenticator version: 6.0.0
- Operating system and version: Windows 10
- Bug description summary: If you accidentally missclick a 2FA code, the app does not allow to cancel it. You have to either touch the key or wait ~30 seconds for the timeout.

Steps to reproduce
-------------------

- Open Yubico Authenticator
- Click on any of the 2fa codes
- Try to cancel the action

Expected result
--------------

Allow us to cancel the action.

Actual results
--------

![imatge](https://user-images.githubusercontent.com/153305/202158098-f77084b3-104c-4979-9fdf-21eb33eaab5a.png)

**Comment by dainnilsson** [comment]
Thanks for your report. Unfortunately this is a limitation in the YubiKey firmware/protocol. Once initiated, the action cannot be cancelled. I can forward this to the firmware team, but unfortunately I don't think this is something that can easily be solved.

**Comment by elboletaire** [comment]
Oh, I thought this was a feature we had before, but if you say it comes from the firmware I'm clearly wrong. It would be a nice feature to have tho, so let's see what the fw team says 😄

**Comment by dainnilsson** [comment]
I've talked to members of our FW team and I *think* I have a somewhat good understanding of this now. Basically: The CCID interface (which is what OATH uses) generally works in a synchronous way: You send a request, then wait for a response. On that level there is no way to do anything from the host side until the request completes (by the user touching the button, or the request timing out). There *IS* a way to abort a CCID command in the specification, but it is not currently implemented by the YubiKey. What's worse is that it also isn't implemented by most (all?) host platforms, so even if it was supported by YubiKey, it wouldn't be accessible from Yubico Authenticator. So... I'm not too hopeful about this becoming supported :(

I'll close this issue for now and maybe we can re-open it if things change.
