### ISSUE TITLE
[6.0.0] No longer able to minimize to tray

### ISSUE THREAD

**Issue by Aaron-P** [Yubico/yubioath-flutter#816]
After upgrading to version 6 on one of my machines the application is no longer able to minimize/close to the windows system tray.

**Comment by yurykk** [comment]
The same on Mac - no option for the app to stay in a system tray

**Comment by drohm** [comment]
Agreed, we need to have a minimize to tray.

**Comment by dainnilsson** [comment]
Thank you for your reports!

Minimize to tray is a feature which we did not implement in Yubico Authenticator 6, at least for the initial version. Our recommendation is to instead pin the app to the dock/taskbar where you can either keep it running by minimizing when not in use, or just close the app and re-open it when needed.

If you would like to see a minimize to tray feature added please help us understand your use-case for it, and why pinning the app to the taskbar isn't a sufficient alternative for you. This will help us in the design and prioritization of new features.

**Comment by yurykk** [comment]
> If you would like to see a minimize to tray feature added please help us understand your use-case for it, and why pinning the app to the taskbar isn't a sufficient alternative for you. This will help us in the design and prioritization of new features.

Dear dainnilsson,

Keeping the app running "minimised" is inconvenient and the UX is very problematic in this case. But on the other side, having icon in the system tray just for opening the app window is not a very different from launching an app from the dock.

The best solution will be to keep the app in a system tray with the ability to copy OTP codes directly from the tray, without switching focus from the application to another app.  Doesn't have to be for all, but for the most frequently used. 
In fact, there are cases when app/page with waiting for OTP is refreshed automatically after detecting focus change. Can't give the example right now, but I had a few cases like that in the past.

**Comment by MrMase** [comment]
I can think of a use case for this feature and that is for users who use the Task View Multiple Desktops function of Windows.

Current behaviour without minimize to system tray is that if I launch the manager from another desktop instance it pulls me back to the desktop where it was originally opened. This is problematic where I then have to copy the code out, find the correct desktop / app instance again and paste in all before time runs out of the code.

**Comment by fabiankle** [comment]
As a user feedback - and I want to stress I am aware that you have to do compromises, so this is not a demand, just a feedback - I must say this really breaks usability for me (and actually some colleagues I spoke to). I used to just click on the tray, select the key I want, pressed the yubi key, had it in my clip board. 
This was just so much more comfortable to version 6 (in which I need to find the desktop window, need to click on the key, then refresh the old key, then click the yubikey, then click the copy field - I do this two digit times a day so I do care), that we downgrade for now to 5.1.
As said, I am aware you cannot consider all needs, but this feature was really appreciated by us!

**Comment by Aaron-P** [comment]
I often have a significant number of applications and/or windows open, and taskbar space is at a premium for me. Keeping it open or pinning it to the taskbar will take up space I would rather not use, and having to close the application after using it and going to the start menu to re-open it when needed is pretty annoying.

**Comment by christian-van-rensen-tng** [comment]
For me, the most important feature of the tray icon was its context menu, allowing to obtain a OTP with just two clicks and without a perceivable context switch.

**Comment by Elijah-C-G** [comment]
This feature in Yubico Authenticator 5 was a time-saver. On version 6, I have to lose focus on a window and then re-focus the window and also make sure the correct input field is active. With version 5, I could right click the Taskbar icon, get my favorited code, and hit Ctrl-V without losing focus. It's such a nice flow.

**Comment by KernalFear** [comment]
I use windows multiple desktops, the solution of always being open means i need to find where its open or close and re open man times, this is a small issue once but on a daily basis many times its a pain. the system tray icon allows access from any desktop much quicker. I have also noticed when left open the app has a tendency to freeze and then I need to use task manager to kill and re open.

**Comment by wumpus42** [comment]
No mention of minimize to system tray in the 6.1.0 release. Until that is re-introduced, I'll stick with 5.x. Minimizing long running apps to the system tray while keeping them easily accessible saves valuable taskbar space. It's not something I'm willing to give up. Hopefully the 5.x version will continue to be supported.

**Comment by drohm** [comment]
I've since gone back to 5.1.0, at least until the 'minimize to systray' option is added back.  Hopefully not too long.

**Comment by KernalFear** [comment]
I am also rolling back to v 5.1.0 I have tried to embrace the change but it is more cumbersome and generally more awkward to use on a day to day basis

**Comment by xlammertink** [comment]
Are there already plans to re-implement this in v6? I'm quite surprised it got removed as this was perceived an issue in version 4 as well (see GitHub issue #125) and back then it got rolled back very quickly.

As mentioned by others: UX-wise it's a huge accessibility feature that allows a user to quickly select a pinned OTP entry with two clicks in the same area of the screen without having to switch from one application to the other. When using multiple desktops in Windows 10 you even need to switch between desktop to access the Authenticator.

**Comment by wumpus42** [comment]
Two and a half months ago @dainnilsson asked for reasons and use cases for "minimize to tray" and hasn't commented since, so I'm not holding my breath on getting it re-implemented in 6.x. Using 5.1.0 'til then. I wonder how many others have rolled back?

**Comment by jan-maria** [comment]
I've also reverted back to 5.x due the same issue - having Authenticator minimized in system tray was way more convenient and easily accessible / taking much less space.

**Comment by dainnilsson** [comment]
> Two and a half months ago @dainnilsson asked for reasons and use cases for "minimize to tray" and hasn't commented since, so I'm not holding my breath on getting it re-implemented in 6.x.

I haven't replied because I don't have any relevant updates to share at this time. This feature is under consideration, but I can't say when, how, or if it will be implemented. We do read all these comments, and they absolutely do factor in.

**Comment by wumpus42** [comment]
> > Two and a half months ago @dainnilsson asked for reasons and use cases for "minimize to tray" and hasn't commented since, so I'm not holding my breath on getting it re-implemented in 6.x.
> 
> I haven't replied because I don't have any relevant updates to share at this time. This feature is under consideration, but I can't say when, how, or if it will be implemented. We do read all these comments, and they absolutely do factor in.

Thanks for the update.

**Comment by JTarasovic** [comment]
I'll quickly add my use case. I use a tiling window manager with many workspaces and a password protected key. There's not really a way to "minimize" the application. I could open it and type in my password every time I need a OTP but I'd probably have to have it save my password so I don't have to type it in every time. I'd rather not do that.

Having my pinned accounts readily accessible in the system tray from every workspace was really convenient. 

I think the new version looks great and seems to work really well otherwise so kudos and thank you for that!

**Comment by X-dark** [comment]
> I'll quickly add my use case. I use a tiling window manager with many workspaces and a password protected key. There's not really a way to "minimize" the application.

Yes exactly.
And, @dainnilsson, you need to understand that the concept of taskbar is only relevant for some window manager whereas there is quite always a systray.
I am using sway on Linux and I currently need to dedicate a full workspace for yubioath to not get in my way when not using it.

**Comment by dainnilsson** [comment]
A few (726) lines of code: https://github.com/Yubico/yubioath-flutter/pull/970/files

Feel free to try out the latest `main` builds, we're hoping to release this with 7.2.0 (no release date as of yet)!

**Comment by wumpus42** [comment]
Nice! Will the minimize action eventually minimize to tray so One doesn't have to choose "Hide Window" from the systray pop-up menu each time?

Thank you!

**Comment by dainnilsson** [comment]
> Nice! Will the minimize action eventually minimize to tray so One doesn't have to choose "Hide Window" from the systray pop-up menu each time?
> 
> Thank you!

We're leaning towards keeping the current behavior as of now. We're trying to avoid having to have a toggle for this in settings, and the standard behavior for the X button probably shouldn't be to minimize the app, but to close it. We did add a keyboard shortcut for minimizing to tray though, Ctrl+W.

**Comment by wumpus42** [comment]
Ok. I'm not sure whether the toolkit supports it, but maybe the "Hide Window" systray menu option could be a toggle? That way the minimize action could act as a minimize to systray if "Hide Window" is on instead of the default minimize to taskbar?

**Comment by fabiankle** [comment]
Hi @dainnilsson ,
this is great! Many thanks for taking the user feedback into account! The new version works great for me. Thank you!
Best,
Fabian

**Comment by KernalFear** [comment]
> > Nice! Will the minimize action eventually minimize to tray so One doesn't have to choose "Hide Window" from the systray pop-up menu each time?
> > Thank you!
> 
> We're leaning towards keeping the current behavior as of now. We're trying to avoid having to have a toggle for this in settings, and the standard behavior for the X button probably shouldn't be to minimize the app, but to close it. We did add a keyboard shortcut for minimizing to tray though, Ctrl+W.

Firstly, thank you for taking the request on and bringing the functionality back. Some feed back it would be nice if the minimise icon minimised to the sys tray rather than the taskbar or provide the option for the behavoiur the same as with the X for close a toggle in the Settings for X to Minimise would be great.

While a shortcut key is also a welcome feature the use of Ctrl+W is problamatic in this works as the close program option on a number of applications. Particularly the web browser I can see me maximising geting my code pasting in to the browser then hitting Ctrl+W to minimise and ending up closing the browser window and having to start again. Ctrl+T maybe as if this is done in the browser it would only open a Tab or Ctrl+M as this is not used as commonly?

Other than this the new Look is great looks much more modern.

Again big thanks for the changes.

**Comment by dainnilsson** [comment]
> @dainnilsson Is it possible to start Authenticator minimized to tray on macOS?

In the current version the state is saved on exit, so if you minimize to tray and then quit the app, the next launch will start minimized.

**Comment by crmb** [comment]
An option to either "reduce to tray (only)" or "close to tray" would be nice.
My (maybe unusual) use case is that i don't use pinned items, only an old-style quick launch bar, and small icons buttons with full text.
