### ISSUE TITLE
Application name display issue on Android

### ISSUE THREAD

**Issue by eukislov** [Yubico/yubioath-flutter#817]
A small suggestion for an Android app.
In the App Drawer on Android (in my case it is Oxygen OS 13, OnePlus 8), the name of the Yubico Authenticator application is not fully displayed.
Please consider changing the app's display name to Yubico Auth or something similar.

![IMG_20221116_205814](https://user-images.githubusercontent.com/108125278/202230733-2f3bad96-0fcc-4091-babe-3193560baa72.jpg)

**Comment by dainnilsson** [comment]
Thank you for the suggestion! Prior to the release we had an internal discussion about this along with several alternatives. The current one ("Yubico Authenticator") was the one we landed on as best, even though it gets truncated.
