### ISSUE TITLE
6.0.0 Click to Copy Feature

### ISSUE THREAD

**Issue by drohm** [Yubico/yubioath-flutter#819]
It would be nice to have a 'click to copy' feature.  Specifically, the click to copy would be the area highlighting the OTP code.  This makes copying codes one click instead of 2 (right-click, copy to clipboard or click the account then click copy to clipboard button).

**Comment by drohm** [comment]
After tinkering with the app, I've discovered double-click will copy the OTP codes.  I couldn't find that mentioned anywhere so I'm pretty happy with this.  The single one-click on the OTP code might be a nice feature that people may like.

**Comment by kaoneko** [comment]
For keyboard users like myself I'd like to add to this that control+c also works! And now I see it's listed in that context menu as a shortcut for copy to clipboard as well, which I hadn't seen of course, being a keyboard user and all. Maybe a keyboard shortcuts section on the Help and about-page, like in the old version, would be nice :)

**Comment by tuck182** [comment]
I used to be able to double-click on the line to copy the code; now I have to double-click on the code itself (which never even showed up before). For my own use case this is just a worse experience (it's just slightly harder to hit that smaller UI element).

Now clicking on an account brings up a menu of options that's identical to the features provided by right-clicking. So that particular interaction seems to provide very little value. I assume it's only there because that's how it works on mobile.

**Comment by JWL2017** [comment]
Bring back the 5.1 double click-touch-auto copy functionality.  The 6.0 UX is a step backwards.

**Comment by persident** [comment]
> Bring back the 5.1 double click-touch-auto copy functionality. The 6.0 UX is a step backwards.

100% agree. Especially on Windows the new behavior degrades many workflows.

**Comment by dainnilsson** [comment]
There are several shortcuts available to both generate and copy the code to clipboard quickly, but they are rather hidden. We will try to make these more obvious, but for reference these are as follows:

* Long-press (mainly intended for touch screen usage) on an Account in the list.
* Double-click (intended for mouse usage) on the code area of the Account (where the code itself or the touch icon is)
* Ctrl/CMD+C when an Account has focus

Note that for any Account that requires touch, this will both trigger the touch prompt, and perform the copy-to-clipboard function.

The reason for not automatically copying to clipboard is that we want this to be an explicit action from the user. On many platforms the clipboard is readable by other apps, and the tradeoffs of using it should be understood by the user. For many this isn't a concern, but we want to leave the choice up to the user. It's important for us that OTPs don't show up in the clipboard by mistake, or without the user knowing.

**Comment by profet23** [comment]
> The reason for not automatically copying to clipboard is that we want this to be an explicit action from the user. On many platforms the clipboard is readable by other apps, and the tradeoffs of using it should be understood by the user. For many this isn't a concern, but we want to leave the choice up to the user. It's important for us that OTPs don't show up in the clipboard by mistake, or without the user knowing.

While this default behavior is certainly understood, it would be nice if we could toggle on/off the auto copy.

The number of clicks/keypresses to get a TOTP token out of the app has drastically increased going from 5.x to 6.x. It has become a very annoying issue. 

Previous (5.x) workflow:

1. Right click on tray icon and click favorited/pinned account.
2. Touch Yubikey
3. Paste TOTP token

Current (6.x) workflow:

1. Open Yubico Authenticator fully (this means losing focus of the app you are currently using)
2. Click account
3. Click refresh/calculate button
4. Touch Yubikey
5. Click copy in the Yubico Authenticator app
6. Switch back to the app asking for credentials
7. Paste TOTP token
8. (Optional but either required now or required as step 1 of the next interaction) Escape out of the currently focused account in Yubico Authenticator.

This is a major step backwards and a major annoyance.

**Comment by dainnilsson** [comment]
@profet23 

> The number of clicks/keypresses to get a TOTP token out of the app has drastically increased going from 5.x to 6.x. It has become a very annoying issue.

As explained previously, a faster workflow with the current (6.x) version is to just double-click on the "code pill" part of the account. This will trigger the code generation (with touch, if required) and copy the resulting code to clipboard.

See also #816 for systray icon support.

**Comment by drohm** [comment]
@dainnilsson is that information posted any where else besides in this ticket?  I only know about it because I'm on this thread.  Is it in the docs?  A quick look-through and I couldn't find anything.

**Comment by dainnilsson** [comment]
It isn't (yet) in any docs, and one reason for that is that the behavior will be slightly changing with the next release of the app (6.2) based on user feedback. We hope to get the docs a bit more up to date soon. In the meantime, the new behavior in 6.2 will be:

- Double-click (or long-press) on the Account list item (not the code pill): Copy to clipboard (generating a new code if needed)
- Single-click on the Code pill (which will look and behave more like a real button): Open the Account details view.

**Comment by Rikj000** [comment]
> The number of clicks/keypresses to get a TOTP token out of the app has drastically increased going from 5.x to 6.x. It has become a very annoying issue.

I fully agree:
- UI wise: The 6.X update has some nice new eye candy.
- Usage wise: The 6.0 update is a terrible downgrade..

> Previous (5.x) workflow:
> 
>     1. Right click on tray icon and click favorited/pinned account.
>     2. Touch Yubikey
>     3. Paste TOTP token

I will not update to any new versions before before above flow is available again.

Usage > UI

**Comment by Duckle29** [comment]
@Rikj000 This is available, has been since March, but I also didn't know. 

Had to find a reddit thread that linked to issue https://github.com/Yubico/yubioath-flutter/issues/816 which had [this comment](https://github.com/Yubico/yubioath-flutter/issues/816#issuecomment-1452425813) that you can either hide the UI by right-clicking the tray and selecting hide, or by ctrl+w.

Pinned accounts will then be available from the tray icon

**Comment by dainnilsson** [comment]
Yubico Authenticator 6.2 has now been released, which moves the "double-click to copy" function from the smaller code-button to the larger account list item (as in 5.x). The code-button now opens the detailed account view instead.
