### ISSUE TITLE
Use consistent tags for releases

### ISSUE THREAD

**Issue by pauby** [Yubico/yubioath-flutter#821]
Looking at the releases, there are some with tags for `yubioath-desktop-5.1.0` there are some with just the version number, `6.0.0` for example. There are some with no assets, there are some with assets. Some point to the releases page on the Yubico website, some you can get from the releases page.

The latest 6.0.0 and .1.0 follow a pattern of just the version number in the tag and the assets in the release. This is great, but are you going to use this going forward?

Inconsistent releases and inconsistent tagging makes it difficult to automate the checking of new versions. 

One thing I also noticed is that 'macOS App Store, Microsoft Store and Play Store' is added to releases. I wanted to make you aware that the [`yubico-authenticator` package](https://community.chocolatey.org/packages/yubico-authenticator) has been available in the Chocolatey Community Repository [since 2017 (version 3.1.0)](https://community.chocolatey.org/packages/yubico-authenticator#versionhistory). It would be useful to add that and help thank the maintainer for their effort.

**Comment by dainnilsson** [comment]
Sorry for the inconsistency in the past! Yes, going forward we will be using the format used for 6.0.0 (and 6.0.1) in terms of both tag names (`x.y.z`) and attached assets. Do note that some releases (like 6.0.1) may be platform specific and may not include artifacts for all supported platforms.

**Comment by pauby** [comment]
Awesome. Thanks for clarifying that.

> Do note that some releases (like 6.0.1) may be platform specific and may not include artifacts for all supported platforms.

I noticed that with the latest release being Android only. That's fine though. As long as I can determine a Windows release using the asset name, that's all I need.

I'll go ahead and close this now. Thanks for your help.
