### ISSUE TITLE
[6.0] Single Account per line regardless of Window Size

### ISSUE THREAD

**Issue by MrMase** [Yubico/yubioath-flutter#822]
Back in v5.x when the window was resized we could have multiple accounts on a single line, now it is 1 account per line regardless of Window size. Please bring back multiple accounts per line for those working on displays of decent resolution e.g.1920 x 1080.

**Comment by braathen** [comment]
Very old issue here, but Gridview is now FINALLY available for both OATH accounts and passkeys in the new 7.1 version just released! I hope you're still with us! 😄 Note that it's now also possible to collapse/hide the menus on both sides for even more space.
