### ISSUE TITLE
[6.0] Multiple Yubikeys

### ISSUE THREAD

**Issue by MrMase** [Yubico/yubioath-flutter#823]
Please reintroduce a drop down to select which Yubikey is active when multiple are connected to the system at the same time due to key limit on hardware.

Currently in v6 you have to hit the More Actions, select the Yubikey and then select which key you want to use, can this be streamlined so that when you hit More Actions all keys are listed at that level, or have a drop down to select without having to go fully into the key.

**Comment by msusta** [comment]
Ouch, didn't notice this issue the first time around when I created the #920, however there's some progress!
@dainnilsson do you want to merge this and #920 ?

**Comment by dainnilsson** [comment]
Closing this now as the device picking has been changed and no longer requires more clicks than in v5. The CTRL+TAB shortcut also allows changing device without using the mouse at all.
