### ISSUE TITLE
Yubico Authenticator 6.0 crashes on VirtualBox Windows 11 Pro client

### ISSUE THREAD

**Issue by jplejacq-quoininc-com** [Yubico/yubioath-flutter#843]
Clean install using winget on Windows 11 Pro client in Virtual Box starts with windows partially visible and then shuts down.

Host: Debian GNU/Linux Bullseye  fully updated
VirtuaBox: 6.1.40_Debian r154048
Client: Windows 11 Pro Version 21H2 (OS Build 22000.1281

Windows Event Log has this message:

Version:1.0
StartHTML:000000224
EndHTML:000019391
StartFragment:000006102
EndFragment:000019359
StartSelection:000006168
EndSelection:000019359
SourceURL:file:///C:/Users/Administrator/AppData/Local/Temp/tmpFE9C.tmp
<BODY id=body 
onload=window.fullyLoaded=true;ToggleSystemElement();>
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR><TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>System</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Provider</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>Name</B>] </TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">Application 
Error</TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>EventID</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">1000</TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>Qualifiers</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0</TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Version</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Level</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">2</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Task</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">100</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Opcode</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Keywords</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0x80000000000000</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>TimeCreated</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>SystemTime</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">2022-11-23T14:32:12.7515884Z</TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>EventRecordID</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">11792</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'"><B>Correlation</B></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Execution</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>ProcessID</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">6208</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD width=12 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=105 noWrap>[ 
<B>ThreadID</B>] </TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0</TD></TR></TBODY></TABLE></DIV></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Channel</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">Application</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>Computer</B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">qipf1y4mle-win</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">
<TABLE>
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 noWrap></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'"><B>Security</B></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></DIV>
<TABLE onclick=Toggle(this) style="CURSOR: hand">
<TBODY>
<TR>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=15 
noWrap><B>-</B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B>EventData</B></TD></TR></TBODY></TABLE>
<DIV>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">authenticator.exe</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">6.0.0.0</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">636a9665</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">VBoxDispD3D.dll</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">6.1.22.44080</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">60899173</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">c0000094</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">0000000000006a5d</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">dec</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">01d8ff4860094c82</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">C:\Program 
Files\WindowsApps\YubicoAB.YubicoAuthenticator_6.0.0.0_x64__pjam772p9bs2g\VFS\ProgramFilesX64\Yubico\Yubico 
Authenticator 6test\authenticator.exe</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">C:\Windows\SYSTEM32\VBoxDispD3D.dll</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">8071f8d8-9e4e-4791-9d28-45488326bab6</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">YubicoAB.YubicoAuthenticator_6.0.0.0_x64__pjam772p9bs2g</TD></TR></TBODY></TABLE>
<TABLE cellSpacing=0 border=0>
<TBODY>
<TR>
<TD width=15 noWrap></TD>
<TD width=15 noWrap></TD>
<TD style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top" width=130 
noWrap><B></B></TD>
<TD 
style="FONT-FAMILY: 'Segoe UI'; VERTICAL-ALIGN: top">AUTHENTICATOR</TD></TR></TBODY></TABLE></DIV></BODY></HTML>

**Comment by dainnilsson** [comment]
This seems to be a bug in VirtualBox: https://www.virtualbox.org/ticket/20851

**Comment by dainnilsson** [comment]
Do you have 2D or 3D acceleration enabled for the VM (I believe it can be found in the Display Settings for the VM)? If you change these settings, does it change the behavior when you launch Yubico Authenticator at all?

**Comment by jplejacq-quoininc-com** [comment]
Yes, I do normal have 3D Acceleration enabled for the graphic controller. When I disabled acceleration, Yubico Authenticator starts up successfully and seems to be working.

Thank you for this workaround. I'm not sure it is a practical long term solution but it does unblock me for testing.

**Comment by dainnilsson** [comment]
Thanks for testing, and I'm glad that gives you a workaround. I would recommend opening a ticket with VirtualBox as that is where the issue seems to be. I'll close this issue since there doesn't seem to be anything for us to address in this project.

**Comment by jplejacq-quoininc-com** [comment]
It's unlikely a VirtualBox issue. Literally no other program has shown this behavior in many years of use.
