### ISSUE TITLE
[Android] 6.x app user interface regression (no ability to set icon for account)

### ISSUE THREAD

**Issue by bperrybap** [Yubico/yubioath-flutter#859]
The 6.x user interface has several regressions. IMO, the new user interface is not overall better than the previous user interface.
Yes there are more codes on the screen at once but it drops some capabilities and has a few issues.

Once such regressions is the inability to assign an icon image to the account.
The older app allowed assigning an icon image to the account which helps with quick recognition/location of the account.
This capability appears to  no longer exist and all previous icon images have been lost.

**Comment by dainnilsson** [comment]
Custom icon support is included in 6.2.0.
