### ISSUE TITLE
[Android] 6.x app user interface regression (can't see full login name)

### ISSUE THREAD

**Issue by bperrybap** [Yubico/yubioath-flutter#861]
The 6.x user interface has several regressions and issues.
Yes there are more codes on the screen at once but it drops some capabilities and has a few issues.

Once such regressions issue is that the app clips the login name when it is long.
This was not an issue with the older app.
Even if you click on the account which brings it up separately on a new screen, the name can still be clipped.
One thing that could help a bit on the main screen is if the fields were moved around a bit.
i.e. 
move the rounded rectangle on the right with the code up a bit
This would allow the username to stretch all the way across the screen allowing a longer name before clipping.
But one the separate screen, you need to figure out how to show the entire name.
There is plenty of room on the screen. Just figure out to place it on the screen.

**Comment by AdamVe** [comment]
Thanks for reporting, we will review the design asap.

**Comment by AdamVe** [comment]
Hi @bperrybap, we released version 6.1.0 last week. There the issuer and account name are rendered fully in the account dialog.
