### ISSUE TITLE
[Android] 6.x [feature request] Disable NFC Sounds

### ISSUE THREAD

**Issue by Stephen-ONeil** [Yubico/yubioath-flutter#863]
Bumping over from the old repo.

> The reader-mode API has a flag FLAG_READER_NO_PLATFORM_SOUNDS that can be used to disable the NFC discovery sounds.
> 
> Please use this as the sounds are quite annoying, especially if you have to tap twice to see a code.

https://github.com/Yubico/yubioath-android/issues/113

For my part, I've only been using the authenticator (on Android) for one day, and while I think it is really cool I'm also getting a little tired of the max volume discovery sounds, haha! Found the above issue while googling for a way to mute it, after finding nothing in the app settings.

**Comment by AdamVe** [comment]
Thanks for bringing this back from the original repo. We will review this feature request again.

**Comment by AdamVe** [comment]
This feature has been implemented in [6.1.0](https://github.com/Yubico/yubioath-flutter/releases/tag/6.1.0) (#901)
