### ISSUE TITLE
App does not remember window position

### ISSUE THREAD

**Issue by edelstone** [Yubico/yubioath-flutter#882]
Problem: I like using the application in a narrow size, justified all the way to the left of my screen. However, after quitting and restarting the app, it always moves towards the center of the screen instead of remaining justified to the side. It's a minor annoyance that was actually fixed at one point in a previous version (#574).

Apple M1 Pro 2021 16" MBP
MacOS Ventura 13.1
Version 6.0.2 (downloaded from Mac App Store)
Yubikey 5C Nano

**Comment by GitPullNow** [comment]
Have the same issue starting from v6. Previous version 5 did not have this issue for me. It does not remember on which screen it is or what size the window should be at.

PC Windows 11 22H2 Build 22621.1194
Dual monitor setup with a 24" (1920x1080) and a 34" Ultrawide (3440x1440)
Yubico Authenticator v6.1.0
Yubikey 5C Nano

**Comment by AdamVe** [comment]
Hi! We have merged support for remembering window position of the app. Currently only **MacOS** and **Windows** platforms are supported.

It is possible to try out the feature by running the build from GitHub. If you do, please, let us know what you think.

**Comment by edelstone** [comment]
Using Production version 6.2.0 and this is working great. Thank you.
