### ISSUE TITLE
[Windows] 6.0.2 Authenticator sometimes crashes while adding new account

### ISSUE THREAD

**Issue by danodemano** [Yubico/yubioath-flutter#891]
Windows 10 Pro 22H2 fully up-to-date. I didn't manage to locate a log file but can provide whatever more is needed. Data from the event viewer here:

Faulting application name: authenticator.exe, version: 6.0.2.0, time stamp: 0x63848af1
Faulting module name: ntdll.dll, version: 10.0.19041.2130, time stamp: 0xb5ced1c6
Exception code: 0xc0000374
Fault offset: 0x00000000000ff6a9
Faulting process id: 0x5824
Faulting application start time: 0x01d92236afe3daf7
Faulting application path: C:\Program Files\Yubico\Yubico Authenticator\authenticator.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 325f7e22-8da5-4553-bc59-a6f643db945e
Faulting package full name: 
Faulting package-relative application ID:

**Comment by danodemano** [comment]
Upon further investigation, seems to also just crash randomly.

**Comment by AdamVe** [comment]
Hi, do you have more information, repro steps would be best. Please let us know if the latest release 6.1.0 has this issue for you as well.

**Comment by danodemano** [comment]
Hi @AdamVe - 6.1.0 appears to have corrected it. Before it would just crash randomly within a few minutes of being open or every 3rd(ish) time while trying to add a new account. It's been running for over and hour now so I think we are good. Have a great day!
