### ISSUE TITLE
Significant keyboard-usability regressions on macOS in v6

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Yubico/yubioath-flutter#911]
Unfortunately, the new Flutter interface seems to be … pretty terrible for accessibility.

Just off the top of my head, a *non-*exhaustive list of the keyboard controls that are no longer functioning, in approximate order of criticality:

- <kbd>⌘</kbd><kbd>W</kbd>, supposed to close the window, has no effect
- <kbd>Esc</kbd> doesn't cancel the 'Touch required' window
- typing arbitrary text after launching the app no longer instantly searches — I have to use my mouse to locate and activate the 'search accounts	' field before being able to search
- Most critically, the generated number is no longer automatically copied to the clipboard; as far as I can tell, the only way to do that is with the mouse (????)

**Comment by moddx** [comment]
All of the above points are valid on Windows as well :(
On top, any 'touch required' account does not revert to hidden after a new code is generated. It instead shows the old code forever, forcing you to click the new 'Calculate' button manually.

**Comment by dainnilsson** [comment]
In general, we're aware that the keyboard shortcuts sometimes seem to stop functioning. Sometimes this is related to an element having focus or not, but it's clearly not always acting the way it is intended to. We're investigating what might be causing this and how to best work around it.

To address some of your points more directly:
* Cmd+W is something we should add. Cmd+Q should currently be working to close the app.
* The prompt for touch cannot be cancelled, which is a limitation in the YubiKey. The old app didn't prevent you from scrolling or pressing other elements, but anything you tried to do with the YubiKey would be blocked until you either complete the touch, or the command timed out. The new approach of blocking the UI while this is in progress is a lot more true to what is actually going on.
* Cmd+F *should* highlight the search field, allowing you to search for accounts. Again, we are aware that this does not always work. We might consider focusing the field automatically on startup.
* There are multiple ways to copy the code: You can use the mouse and double-click on the code itself in the list view, or right-click and select copy. Or, click on the account entry to open the single account view, and press the Copy button there. With the keyboard you should be able to select the account with the arrow keys and press Cmd+C.

**Comment by moddx** [comment]
> There are multiple ways to copy the code: You can use the mouse and double-click on the code itself in the list view, or right-click and select copy. Or, click on the account entry to open the single account view, and press the Copy button there. With the keyboard you should be able to select the account with the arrow keys and press Cmd+C.

Double-clicking the code itself does the trick! ♥
That's really not obvious when upgrading from < v6  on PC. Maybe a visual highlight on hovering the code could help?

**Comment by sarndt** [comment]
Maybe it makes sense to give an option of what "Enter" should do.
I didn't even know that I can just press ctrl+c in the list when using keyboard only to get the touch prompt, and have the same experience as before basically.

Might be an option to introduce a 3-dot menu to the entries, and return the Enter key to by default just try to copy a valid code.
By reading this issue though, I figured out that when I use ctrl+c instead, the old flow is still there, so that works for me too.
