### ISSUE TITLE
QR Code scan in Wayland KDE Plasma

### ISSUE THREAD

**Issue by stefan-matic** [Yubico/yubioath-flutter#939]
The current linux [guide](https://github.com/Yubico/yubioath-flutter/blob/main/resources/linux/README.adoc) instructs using `gnome-screenshot` for Wayland. The `gnome-screenshot` doesn't work on KDE Plasma when running Wayland. 

Is there any possibility to add support for [Spectacle](https://invent.kde.org/graphics/spectacle)?

**Comment by dainnilsson** [comment]
This has now been added by 14ca9f0f1320623c421c0737d43128b0213fac79 to be included in the next release. In the meantime if you'd like to test the functionality, feel free to try out the build from https://github.com/Yubico/yubioath-flutter/actions/runs/4124055324 and let us know your results!

**Comment by liferooter** [comment]
I suggest to use screenshot portal:

https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Screenshot

This is the only working and universal solution

**Comment by stefan-matic** [comment]
@dainnilsson Seems to work great for me! Thank you, closing this.

@liferooter If the screenshot portal seems like a better option for the future, let's open another issue for it.

**Comment by liferooter** [comment]
> @liferooter If the screenshot portal seems like a better option for the future, let's open another issue for it.

I've opened an [issue](#1010)
